# -*- coding: utf-8 -*-
"""
/***************************************************************************
 GPVContour
                                 A QGIS plugin
 Make contour  from GPV
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                             -------------------
        begin                : 2020-12-29
        copyright            : (C) 2020 by Naoya Nishibayashi
        email                : naoya.bayashi@gmail.com
        git sha              : $Format:%H$
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
 This script initializes the plugin, making it known to QGIS.
"""


# noinspection PyPep8Naming
def classFactory(iface):  # pylint: disable=invalid-name
    """Load GPVContour class from file GPVContour.

    :param iface: A QGIS interface instance.
    :type iface: QgsInterface
    """
    #
    from .gpv_contour import GPVContour
    return GPVContour(iface)
